[package]
name = "obliteration"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
context = { path = "../context" }
emulator = { path = "../emulator" }
error = { path = "../error" }
pkg = { path = "../pkg" }
