[package]
name = "obliteration"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
libc = "0.2"
memmap2 = "0.5"
sdl2 = { version = "0.35", features = ["static-link", "bundled"] }
