[package]
name = "core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
context = { path = "../context" }
error = { path = "../error" }
pkg = { path = "../pkg" }
pup = { path = "../pup" }
