name: CI (Linux)
on:
  workflow_call:
jobs:
  build:
    name: Linux
    runs-on: ubuntu-20.04 # We cannot use 22.04 due to Vulkan SDK does not available.
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install system dependencies
      run: |
        wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -

        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.3.224-focal.list https://packages.lunarg.com/vulkan/1.3.224/lunarg-vulkan-1.3.224-focal.list
        sudo apt-get update
        sudo apt-get install -y libxkbcommon-dev vulkan-sdk

        echo "VULKAN_SDK=/usr" >> $GITHUB_ENV
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        cache: true
        cache-key-prefix: ${{ runner.os }}-install-qt-action
        version: 6.2.*
    - name: Initialize VCPKG
      run: ./vcpkg/bootstrap-vcpkg.sh
    - name: Cache VCPKG
      uses: actions/cache@v3.0.11
      id: cache-vcpkg
      with:
        path: /usr/local/share/vcpkg/packages
        key: ${{ runner.os }}-VCPKG-${{ hashFiles('**/CMakeLists.txt', '**/Cargo.lock', '**/Cargo.toml') }}
    - if: ${{ steps.cache-vcpkg.outputs.cache-hit != 'true' }}
      name: Install VCPKG packages
      run: ./vcpkg-restore.sh
    - name: Cache CMake Build Files
      uses: actions/cache@v3.0.11
      id: cache-cmake
      with:
        path: |
          /home/runner/work/obliteration/obliteration/build
          /home/runner/work/obliteration/obliteration/src/target
        key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt', '**/Cargo.lock', '**/Cargo.toml', '.github/workflows/*.yml') }}
    - name: Run CMake
      run: cmake -B build -D CMAKE_BUILD_TYPE=Release -- --parallel 2
    - name: Build
      run: cmake --build build -- --parallel 2
