name: CI
on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
concurrency: ci-${{ github.ref }}
jobs:
  build-windows:
    name: Build (Windows)
    runs-on: windows-2019 # Latest Qt 5 only support MSVC 2019
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
    - name: Install Vulkan SDK
      run: |
        Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/1.3.224.1/windows/VulkanSDK-1.3.224.1-Installer.exe" -OutFile VulkanSDK.exe
        .\VulkanSDK.exe --root C:\VulkanSDK  --accept-licenses --default-answer --confirm-command install
        echo "VULKAN_SDK=C:\VulkanSDK" >> $env:GITHUB_ENV
    - name: Initialize VCPKG
      run: .\vcpkg\bootstrap-vcpkg.bat
    - name: Install VCPKG packages
      run: .\vcpkg-restore.ps1
    - name: Run CMake
      run: cmake -B build -S source -D KYTY_FINAL=1
    - name: Build
      run: cmake --build build --config Release
  build-linux:
    name: Build (Linux)
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Install dependencies
      run: |
        wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -

        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.3.224-focal.list https://packages.lunarg.com/vulkan/1.3.224/lunarg-vulkan-1.3.224-focal.list
        sudo apt-get update
        sudo apt-get install -y qt5-default qttools5-dev vulkan-sdk

        echo "VULKAN_SDK=/usr" >> $GITHUB_ENV
    - name: Initialize VCPKG
      run: ./vcpkg/bootstrap-vcpkg.sh
    - name: Install VCPKG packages
      run: ./vcpkg-restore.sh
    - name: Run CMake
      run: cmake -B build -S source -D CMAKE_BUILD_TYPE=Release -D KYTY_FINAL=1
    - name: Build
      run: cmake --build build
