name: CI
on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
concurrency: ci-${{ github.ref }}
jobs:
  build-windows:
    name: Build (Windows)
    runs-on: windows-2019 # Qt 6.2 only support MSVC 2019.
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: 6.2.*
    - name: Install Vulkan SDK
      run: |
        Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/1.3.224.1/windows/VulkanSDK-1.3.224.1-Installer.exe" -OutFile VulkanSDK.exe
        .\VulkanSDK.exe --root C:\VulkanSDK  --accept-licenses --default-answer --confirm-command install
        echo "VULKAN_SDK=C:\VulkanSDK" >> $env:GITHUB_ENV
    - name: Initialize VCPKG
      run: .\vcpkg\bootstrap-vcpkg.bat
    - name: Install VCPKG packages
      run: .\vcpkg-restore.ps1
    - name: Run CMake
      run: cmake -B build -A x64
    - name: Build
      run: cmake --build build --config Release
    - name: Export artifacts
      run: cmake --install build --prefix dist
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: obliteration-windows
        path: dist
  build-linux:
    name: Build (Linux)
    runs-on: ubuntu-20.04 # We cannot use 22.04 due to Vulkan SDK does not available.
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: 6.2.*
    - name: Install Vulkan SDK
      run: |
        wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -

        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.3.224-focal.list https://packages.lunarg.com/vulkan/1.3.224/lunarg-vulkan-1.3.224-focal.list
        sudo apt-get update
        sudo apt-get install -y vulkan-sdk

        echo "VULKAN_SDK=/usr" >> $GITHUB_ENV
    - name: Initialize VCPKG
      run: ./vcpkg/bootstrap-vcpkg.sh
    - name: Install VCPKG packages
      run: ./vcpkg-restore.sh
    - name: Run CMake
      run: cmake -B build -D CMAKE_BUILD_TYPE=Release
    - name: Build
      run: cmake --build build
